# -*- coding: utf-8 -*-
"""Notebook_do_Aluno_Python_sem_Susto_Aula_Nivelamento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IN9G_E2jzdNaFtFiQt5gR2NeFprHHNI1

# Python sem Susto
## Aula de Nivelamento — Estruturas, Erros, Módulos e Objetos

Este notebook foi pensado para acompanhar uma aula ao vivo de aproximadamente **3 horas**.

A proposta não é decorar sintaxe. Vamos trabalhar em ciclos curtos:

**problema → hipótese → conceito → execução → exercício → erro → investigação → conclusão**

Ao final da aula, você deverá conseguir:

- manipular strings, listas, tuplas, dicionários e conjuntos;
- consultar, incluir, alterar e remover elementos;
- percorrer coleções com `for`;
- reconhecer exceções comuns;
- ler mensagens de erro e tracebacks básicos;
- tratar erros previsíveis com `try` e `except`;
- entender módulos e imports;
- reconhecer e usar classes e objetos simples;
- compreender `__init__`, atributos e métodos.

> **Regra da aula:** sempre que houver uma pergunta “antes de executar”, tente responder primeiro. Depois rode a célula e compare sua hipótese com o comportamento real.

# 0. Aquecimento — antes de aprender, tente ler

Observe o código abaixo **sem executar ainda**.

Tente prever o que cada `print()` exibirá.
"""

codigo = "PED-2026-0042"

produtos = ["Mouse", "Teclado", "Monitor"]

cliente = {
    "nome": "Ana",
    "email": "ana@email.com"
}

print(codigo[0])
print(codigo[-1])
print(produtos[1])
print(cliente["nome"])

"""### Antes de executar

Responda mentalmente ou em uma célula Markdown:

1. O que será exibido por `codigo[0]`?
2. O que significa o índice `-1`?
3. O que será exibido por `produtos[1]`?
4. Por que `cliente["nome"]` usa uma palavra dentro dos colchetes em vez de um número?

Agora execute a célula e compare sua previsão com o resultado.

### O que queremos observar

- Strings e listas podem ser acessadas por posição.
- Dicionários são normalmente acessados por chave.
- Índices de sequências começam em `0`.
- Índices negativos permitem acessar posições a partir do final.

---

# 1. Strings, indexação e slicing

Uma `str` representa texto.

Mas uma string também pode ser vista como uma **sequência de caracteres**.

Considere:
"""

codigo = "PED-2026-0042"
print(codigo)

"""Visualmente:

```text
P   E   D   -   2   0   2   6   -   0   0   4   2
0   1   2   3   4   5   6   7   8   9  10  11  12
```

## Indexação

Indexar significa acessar uma posição específica.
"""

codigo = "PED-2026-0042"

print(codigo[0])
print(codigo[1])
print(codigo[-1])
print(codigo[-2])

"""## Slicing

Slicing significa obter uma faixa da sequência.

A forma básica é:

```python
sequencia[inicio:fim]
```

O índice inicial é incluído. O índice final **não** é incluído.
"""

codigo = "PED-2026-0042"

print(codigo[0:3])
print(codigo[4:8])
print(codigo[9:13])
print(codigo[-4:])

"""## Exercício 1 — Decodificando um pedido

A variável abaixo contém três informações:

- tipo: `PED`
- ano: `2026`
- número: `0042`

Complete o código usando apenas indexação ou slicing.
"""

codigo = "PED-2026-0042"

tipo = codigo[0:3]
ano = codigo[4:8]
numero = codigo[9:14]

print(tipo)
print(ano)
print(numero)

"""### Pista 1

Use o desenho de índices:

```text
P   E   D   -   2   0   2   6   -   0   0   4   2
0   1   2   3   4   5   6   7   8   9  10  11  12
```

### Pista 2

Lembre que o limite final do slicing não é incluído.

"""

#Faça aqui o exeercício 1

"""## Experimento — strings são imutáveis

Tente alterar apenas o primeiro caractere:
"""

codigo = "PED-2026-0042"

# Remova o # da linha abaixo e execute.
 codigo[0] = "X"

"""Quando a linha for executada, Python produzirá um `TypeError`.

Isso acontece porque strings são **imutáveis**: depois de criadas, não alteramos seus caracteres individualmente.

Podemos criar outra string:

```python
codigo = "XED-2026-0042"
```

mas não modificar uma posição isolada da string original.

---

# 2. Listas e tuplas

Agora imagine vários produtos:

```python
produto1 = "Mouse"
produto2 = "Teclado"
produto3 = "Monitor"
```

Funciona, mas não escala bem.

Uma lista representa uma coleção ordenada e mutável.
"""

produtos = [
    "Mouse",
    "Teclado",
    "Monitor"
]

print(produtos)
print(produtos[0])
print(produtos[-1])
print(len(produtos))

"""## Operações básicas com listas

Vamos trabalhar com quatro perguntas:

1. Como consultar?
2. Como incluir?
3. Como alterar?
4. Como remover?
"""

produtos = ["Mouse", "Teclado", "Monitor"]

# Consulta
print(produtos[1])

# Inclusão
produtos.append("Headset")
print(produtos)

# Alteração
produtos[1] = "Teclado mecânico"
print(produtos)

# Remoção
produtos.remove("Mouse")
print(produtos)

"""## Exercício 2 — Catálogo de produtos

Comece com:
"""

produtos = [
    "Mouse",
    "Teclado",
    "Monitor"
]



# 1. Exiba o primeiro produto.
print(produtos[0])
# 2. Exiba o último produto.
print(produtos[2])
# 3. Adicione "Headset".
produtos.append("Headset")
print(produtos)
# 4. Troque "Teclado" por "Teclado mecânico".
produtos [1] = "Teclado mecanico."
print(produtos)

# 5. Remova "Mouse".
produtos.remove("Mouse")
print(produtos)
# 6. Exiba a quantidade final de produtos.
print(len(produtos))

#Faça aqui o exercício 2

"""## Tuplas

Uma tupla também é uma sequência, mas sua estrutura não é mutável.

Exemplo:
"""

dimensoes_monitor = (1920, 1080)

print(dimensoes_monitor[0])
print(dimensoes_monitor[1])

"""Agora tente alterar:"""

dimensoes_monitor = (1920, 1080)

# Remova o # e execute:
# dimensoes_monitor[0] = 1280

"""O erro mostra uma diferença fundamental:

- `list`: sequência mutável;
- `tuple`: sequência cuja estrutura não pode ser alterada diretamente.

## Exercício rápido

Responda sem código:

- uma coleção de produtos que receberá novos itens → lista ou tupla?
R: lista
- uma coordenada `(latitude, longitude)` que não será alterada elemento por elemento → lista ou tupla?
R: tupla

O objetivo não é decorar “qual é melhor”. É relacionar a estrutura ao uso que faremos dela.

# Faça aqui o Exercício Rápido

---

# 3. Dicionários e conjuntos

Considere:
"""

cliente = ["Ana", "ana@email.com", 24]

print(cliente[1])

"""Funciona, mas o que significa a posição `1`?

Precisamos conhecer a convenção.

Com um dicionário podemos associar uma **chave** a um **valor**:
"""

cliente = {
    "nome": "Ana",
    "email": "ana@email.com",
    "idade": 24
}

print(cliente["email"])

"""## Operações básicas em dicionários"""

cliente = {
    "nome": "Ana",
    "email": "ana@email.com",
    "idade": 24
}

# Consulta
print(cliente["nome"])

# Inclusão
cliente["cidade"] = "São Paulo"
print(cliente)

# Alteração
cliente["idade"] = 25
print(cliente)

# Remoção
del cliente["cidade"]
print(cliente)

"""## Exercício 3A — Atualizando um cliente

Use o dicionário:
"""

cliente = {
    "nome": "Ana",
    "email": "ana@email.com",
    "idade": 24
}

# 1. Exiba o e-mail.
print(cliente["email"])
# 2. Inclua a cidade "São Paulo".
cliente ["cidade"] = "São paulo"
print(cliente)
# 3. Altere a idade para 25.
cliente ["idade"] = 25
print(cliente)

# 4. Remova a cidade.
del cliente ["cidade"]
print(cliente)
# 5. Exiba o dicionário final.
print(cliente)

#Faça aqui o Exercício 3A

"""## Experimento — chave inexistente

Execute:
"""

cliente = {
    "nome": "Ana"
}

# Remova o # e execute:
# print(cliente["telefone"])

"""O resultado será um `KeyError`.

Por enquanto, não vamos tratar o erro. Apenas observe:

- o tipo da exceção;
- a chave informada na mensagem.

Voltaremos a isso na parte de erros.

## Conjuntos (`set`)

Considere:
"""

clientes = [
    "Ana",
    "Carlos",
    "Ana",
    "Beatriz",
    "Carlos",
    "Ana"
]

clientes_unicos = set(clientes)

print(clientes_unicos)

"""Um `set` é útil quando queremos trabalhar com valores únicos.

Também podemos:
"""

clientes_unicos = {"Ana", "Carlos"}

clientes_unicos.add("Beatriz")

print("Ana" in clientes_unicos)

clientes_unicos.discard("Carlos")

print(clientes_unicos)

"""## Exercício 3B — Clientes sem repetição

Use:
"""

clientes = [
    "Ana",
    "Carlos",
    "Ana",
    "Beatriz",
    "Carlos",
    "Ana"
]

# 1. Crie um conjunto chamado clientes_unicos.
clientes_unicos = set(clientes)
# 2. Exiba o conjunto.
print(clientes_unicos)
# 3. Adicione "Marina".
clientes_unicos.add("Marina")
print(clientes_unicos)
# 4. Verifique se "Ana" está presente.
if "Ana" in clientes_unicos:
  print("Esta presente")
else:
  print("Não está presente")
# 5. Exiba o conjunto final.
print(clientes_unicos)

#Faça Aqui o Exercício 3B

"""---

# 4. Iteração sobre coleções

Agora temos vários pedidos:
"""

pedidos = [
    {
        "id": "PED-001",
        "cliente": "Ana",
        "produto": "Mouse",
        "quantidade": 2,
        "preco": 120.0
    },
    {
        "id": "PED-002",
        "cliente": "Carlos",
        "produto": "Teclado",
        "quantidade": 1,
        "preco": 250.0
    },
    {
        "id": "PED-003",
        "cliente": "Ana",
        "produto": "Monitor",
        "quantidade": 1,
        "preco": 900.0
    }
]

"""Se tivermos centenas de pedidos, não queremos escrever:

```python
print(pedidos[0])
print(pedidos[1])
print(pedidos[2])
...
```

Podemos iterar:
"""

for pedido in pedidos:
    print(pedido)

"""A cada repetição, `pedido` representa um dos elementos da lista.

Podemos acessar os campos do dicionário:
"""

for pedido in pedidos:
    print(
        pedido["cliente"],
        "-",
        pedido["produto"]
    )

"""## Exercício 4 — Processando todos os pedidos

Faça três tarefas:

1. exiba `id`, cliente e produto de cada pedido;
2. calcule o valor total de cada pedido;
3. construa um conjunto com os clientes únicos.
"""

pedidos = [
    {
        "id": "PED-001",
        "cliente": "Ana",
        "produto": "Mouse",
        "quantidade": 2,
        "preco": 120.0
    },
    {
        "id": "PED-002",
        "cliente": "Carlos",
        "produto": "Teclado",
        "quantidade": 1,
        "preco": 250.0
    },
    {
        "id": "PED-003",
        "cliente": "Ana",
        "produto": "Monitor",
        "quantidade": 1,
        "preco": 900.0
    }
]

# Sua solução aqui
clientes_unicos = set()
for pedido in pedidos:
  print(f"{pedido["id"]} {pedido["cliente"]} {pedido["produto"]}")
  print(f"O valor total é: {pedido["quantidade"] * pedido["preco"]}")

  clientes_unicos.add(pedido["cliente"])
print(clientes_unicos)

"""### Pista 1

A estrutura de repetição começa assim:

```python
for pedido in pedidos:
```

### Pista 2

O total é:

```python
pedido["quantidade"] * pedido["preco"]
```

### Pista 3

Para clientes únicos:

```python
clientes_unicos = set()
```

e, durante a iteração:

```python
clientes_unicos.add(...)
```

"""

#Faça aqui o exercício 4

"""Observe quantos conceitos aparecem juntos:

- lista;
- dicionário;
- consulta por chave;
- conjunto;
- iteração.

Eles não são capítulos isolados. São ferramentas combináveis.

---

# 5. Laboratório de erros — faça o programa quebrar

Agora a missão é propositalmente gerar erros e **ler o que o Python informa**.

Você não precisa decorar os nomes antes.

Execute cada célula, observe o traceback e anote:

1. tipo da exceção;
2. mensagem;
3. operação que causou o problema.

## Erro A
"""

# Execute esta célula:
print(total_pedido)

"""## Erro B"""

# Execute esta célula:
"10" + 5

"""## Erro C"""

# Execute esta célula:
int("dez")

"""## Erro D"""

produtos = ["Mouse", "Teclado"]

# Execute:
print(produtos[10])

"""## Erro E"""

cliente = {
    "nome": "Ana"
}

# Execute:
print(cliente["telefone"])

"""## Erro F"""

cliente = {
    "nome": "Ana"
}

# Execute:
cliente.append("Carlos")

"""## Confira

Os erros observados devem incluir:

| Situação | Exceção |
|---|---|
| nome não definido | `NameError` |
| operação incompatível entre tipos | `TypeError` |
| valor inadequado para conversão | `ValueError` |
| índice inexistente | `IndexError` |
| chave inexistente | `KeyError` |
| atributo/método inexistente | `AttributeError` |

Não transforme isso em uma lista para decorar.

A pergunta mais importante é:

> **O que eu estava tentando fazer quando essa exceção apareceu?**

---

# 6. Leitura básica de traceback

Considere o código:
"""

class Pedido:
    def __init__(self, dados):
        self.dados = dados

    def calcular_total(self):
        return (
            self.dados["preco"]
            * self.dados["quantidade"]
        )


dados = {
    "produto": "Mouse",
    "quantidade": 2,
    "preco":50
}

pedido = Pedido(dados)

# Remova o # e execute:
print(pedido.calcular_total())

"""Antes de corrigir, responda:

1. Qual exceção apareceu?
R: KeyError: 'preco'
2. Qual chave está indicada na mensagem?
R? A chave "preco"
3. Em qual operação a falha ocorreu?
R: Na hora de buscar  "preco" dentro do dicionario
4. O problema está na classe inteira ou em uma consulta específica?
R: O problema esta numa consulta específica na hora procurar o "preco"

### Estratégia simples para tracebacks

Quando o traceback for curto:

1. comece pela última linha;
2. identifique o tipo da exceção;
3. leia a mensagem;
4. procure a linha indicada;
5. compare o dado real com o dado esperado.

"""

#Faça aqui o exercício 6

"""O objetivo aqui não é “fazer sumir o erro”.

É conseguir descrevê-lo tecnicamente:

> A execução tentou consultar a chave `preco` em um dicionário que não possuía essa chave.

---

# 7. `try` e `except`

Nem toda falha representa um defeito no código.

Considere:
"""

entrada = input("Digite a quantidade: ")

# Teste primeiro com 3.
# Depois teste com "três".

# Remova o #:
# quantidade = int(entrada)
# print(quantidade)

"""`int("3")` funciona.

`int("três")` produz `ValueError`.

Essa é uma situação previsível quando recebemos entrada do usuário.

Podemos tratar:
"""

try:
    quantidade = int(
        input("Digite a quantidade: ")
    )

    print("Quantidade informada:", quantidade)

except ValueError:
    print(
        "Quantidade inválida. Digite um número inteiro."
    )

"""Leia a estrutura:

```python
try:
    # operação que pode gerar uma exceção conhecida

except ValueError:
    # comportamento para esse caso
```

O objetivo não é esconder qualquer erro.

Estamos dizendo:

> Se esta exceção específica acontecer, sei o que fazer.

## Exercício 5 — Preço digitado pelo usuário

Leia um preço com `input()`, converta para `float` e trate `ValueError`.

Quando a entrada for inválida, exiba:

```text
Preço inválido.
```
"""

#Faça aqui o exercício 5
try:
  preco = float(input("Digite o preco:  "))

  print("O preco do produto é:  ",preco)

except ValueError:
  print("Valor do produto invalido. Digite um valor float")

"""## Um cuidado importante

Evite usar isto como padrão:

```python
try:
    ...
except:
    ...
```

Capturar qualquer erro pode esconder problemas diferentes daquele que você pretendia tratar.

Nesta aula, prefira exceções específicas quando souber qual falha espera.

---

# 8. Módulos, `import` e `from ... import`

Quando o código cresce, organizar responsabilidades em módulos ajuda na leitura e reutilização.

Primeiro, um módulo da biblioteca padrão:
"""

import math

print(math.sqrt(16))

"""Agora:"""

from math import sqrt

print(sqrt(16))

"""A operação é a mesma.

O que muda é a forma de importar e chamar.

### Forma 1

```python
import math
math.sqrt(16)
```

### Forma 2

```python
from math import sqrt
sqrt(16)
```

## Criando um módulo simples no Colab

A célula abaixo utiliza `%%writefile`, um recurso do ambiente Colab/Jupyter para criar um arquivo.

**Esse comando não faz parte do conteúdo cobrado da aula.**

Ele apenas nos ajuda a simular dois arquivos Python diferentes.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile calculos.py
# 
# def calcular_total(preco, quantidade):
#     return preco * quantidade

"""Agora importe o módulo:"""

import calculos

resultado = calculos.calcular_total(
    120,
    2
)

print(resultado)

"""E compare:"""

from calculos import calcular_total

resultado = calcular_total(
    120,
    2
)

print(resultado)

"""## Exercício 6 — Identifique a origem

Responda:

1. Em `import calculos`, qual é o módulo?
R: O modulo é calculos
2. Em `calculos.calcular_total(...)`, qual função estamos utilizando?
R: Estamos utilizando a funcao calcular_total()
3. Em `from calculos import calcular_total`, o que muda na chamada?
R: A diferenca é que aqui eu ja deixo a mostra quais modulos eu estou trazendo do arquivo.
4. Qual forma deixa explícito, na própria chamada, de qual módulo veio a função?
 R: from calculos import calcular_total

O foco deste exercício é leitura de código.

# Responda o exercício 6

---

# 9. Classes, objetos, atributos, métodos e `__init__`

Até agora um pedido poderia ser representado assim:
"""

pedido = {
    "cliente": "Ana",
    "produto": "Mouse",
    "quantidade": 2,
    "preco": 120.0
}

print(pedido)

"""Esse dicionário funciona.

Mas existe também um comportamento relacionado ao pedido:

**calcular seu total**.

Podemos representar dados e comportamento em uma classe.
"""

class Pedido:

    def __init__(
        self,
        cliente,
        produto,
        quantidade,
        preco
    ):
        self.cliente = cliente
        self.produto = produto
        self.quantidade = quantidade
        self.preco = preco

    def calcular_total(self):
        return self.quantidade * self.preco

"""Agora podemos criar um objeto:"""

pedido = Pedido(
    "Ana",
    "Mouse",
    2,
    120.0
)

print(pedido.cliente)
print(pedido.produto)
print(pedido.preco)
print(pedido.calcular_total())

"""## Vocabulário essencial

### Classe

```python
class Pedido:
```

Define o tipo e seus comportamentos.

### Instanciação

```python
pedido = Pedido(...)
```

É o processo de criação de um objeto a partir da classe.

### Objeto

`pedido` referencia a instância criada.

### Atributo

```python
pedido.preco
```

É um dado associado ao objeto.

### Método

```python
pedido.calcular_total()
```

É um comportamento definido na classe.

### `__init__`

É o método usado aqui para inicializar o estado da instância.

### `self`

Dentro dos métodos, `self` representa a instância sobre a qual o método está operando.

## Exercício 7 — Complete a classe

Complete apenas o método `calcular_total()`.
"""

class Pedido:

    def __init__(
        self,
        cliente,
        produto,
        quantidade,
        preco
    ):
        self.cliente = cliente
        self.produto = produto
        self.quantidade = quantidade
        self.preco = preco

    def calcular_total(self):
        return self.preco * self.quantidade


pedido = Pedido(
    "Ana",
    "Mouse",
    2,
    120.0
)

print(pedido.calcular_total())

#Faça aqui o exercício 7

"""## Exercício 8 — Duas instâncias, dois estados

Crie dois pedidos:

- Ana, Mouse, quantidade 2, preço 120.0
- Carlos, Teclado, quantidade 1, preço 250.0

Depois exiba:

- cliente;
- produto;
- total.

Use uma lista e um `for`.
"""

# Sua solução aqui
class Pedido:
  def __init__(self, cliente, produto, quantidade, preco):
    self.cliente = cliente
    self.produto = produto
    self.quantidade = quantidade
    self.preco = preco

  def calcular_total(self):
    return self.preco * self.quantidade

pedido1 = Pedido("Ana", "Mouse", 2, 120)
pedido2 = Pedido("Carlos", "Teclado", 1, 250)

lista_pedido = (pedido1, pedido2)

for p in lista_pedido:
  print(p.cliente)
  print(p.produto)
  print(p.calcular_total())
  print("-------------------")

"""### Pista

Você pode começar assim:

```python
pedidos = [
    Pedido(...),
    Pedido(...)
]

for pedido in pedidos:
    ...
```

---

# 10. Desafio integrador

Agora vamos combinar apenas os conceitos estudados nesta aula.

Você possui a classe:
"""

class Pedido:

    def __init__(
        self,
        identificador,
        cliente,
        produto,
        quantidade,
        preco
    ):
        self.identificador = identificador
        self.cliente = cliente
        self.produto = produto
        self.quantidade = quantidade
        self.preco = preco

    def calcular_total(self):
        return self.quantidade * self.preco

"""Crie três objetos:

- `PED-001`, Ana, Mouse, 2, 120.0
- `PED-002`, Carlos, Teclado, 1, 250.0
- `PED-003`, Ana, Monitor, 1, 900.0

Depois:

1. armazene os objetos em uma lista;
2. percorra a lista com `for`;
3. exiba id, cliente, produto e total;
4. crie um `set` com os nomes dos clientes;
5. exiba os clientes únicos.

### Pista 1

Crie:

```python
pedidos = [
    Pedido(...),
    Pedido(...),
    Pedido(...)
]
```

### Pista 2

Crie o conjunto antes do `for`:

```python
clientes_unicos = set()
```

### Pista 3

Durante a iteração:

```python
clientes_unicos.add(pedido.cliente)
```
"""



# Faça aqui o Desafio integrador

class Pedido():
  def __init__(self, identificador, cliente, produto, quantidade, preco):

    self.identificador = identificador
    self.cliente = cliente
    self.produto = produto
    self.quantidade = quantidade
    self.preco = preco


  def calcular_total(self):
    return self.quantidade * self.preco



pedidos = [

    Pedido("PED-001", "Ana", "Mouse", 2, 120.0),
    Pedido("PED-002", "Carlos", "Teclado", 1, 250.0),
    Pedido("PED-003", "Ana", "Monitor", 1, 900.0)
]

clientes_unicos = set()

for p in pedidos:
  print(p.identificador)
  print(p.cliente)
  print(p.produto)
  print(p.calcular_total())
  print("-------------------")
  clientes_unicos.add(p.cliente)

print(clientes_unicos)

"""---

# 11. Desafio final de leitura

Agora não escreva nada ainda.

Leia:
"""

class Produto:

    def __init__(
        self,
        nome,
        categoria,
        preco
    ):
        self.nome = nome
        self.categoria = categoria
        self.preco = preco

    def exibir(self):
        print(
            self.nome,
            self.preco
        )


produtos = [
    Produto(
        "Mouse",
        "hardware",
        120.0
    ),
    Produto(
        "Teclado",
        "hardware",
        250.0
    ),
    Produto(
        "Editor",
        "software",
        80.0
    )
]


categorias = set()


for produto in produtos:
    categorias.add(
        produto.categoria
    )

    produto.exibir()


print(categorias)

"""Responda:

1. Qual é a classe?
R: Produto
2. Quantos objetos foram instanciados?
R: Foram 3 objetos
3. Qual variável contém uma lista?
R: A variavel produtos
4. Qual variável contém um conjunto?
R: A variavel categorias
5. Quais são os atributos?
R: nome, categoria e preco
6. Qual é o método?
R: O metodo é o exibir
7. Onde ocorre a iteração?
R: A interacao ocorre dentro da lista produto ao darmos valores ao objetos criados e na hora de imprimir os valores na tela.
8. Por que `set` faz sentido para `categorias`?
R: porque aqui estamos crianddo categorias unicas
9. O que `self` representa dentro de `exibir()`?
10. O que `__init__` está fazendo?
R: Ele serve para conseguirmos acessar os valores atribudos na classe
R: ele esta iniciando o objeto dando a permissão para darmos valores aos atributos

Se você consegue explicar esse programa, a aula cumpriu seu objetivo principal.

---

# 12. Checklist de saída

Ao final da aula, verifique:

- [xa] Consigo diferenciar `str`, `list`, `tuple`, `dict` e `set`.
- [ ] Sei usar indexação simples.
- [ ] Sei interpretar slicing básico.
- [x] Sei consultar, incluir, alterar e remover elementos quando a estrutura permite.
- [x] Consigo percorrer uma coleção com `for`.
- [ ] Reconheço `NameError`, `TypeError`, `ValueError`, `IndexError`, `KeyError` e `AttributeError`.
- [ ] Sei começar a ler um traceback.
- [ ] Entendo para que servem `try` e `except`.
- [x] Entendo o conceito básico de módulo.
- [x] Sei diferenciar `import modulo` de `from modulo import nome`.
- [x] Reconheço uma classe.
- [x] Sei o que é um objeto.
- [ ] Entendo o que significa instanciar.
- [x] Reconheço atributos e métodos.
- [ ] Entendo o papel básico de `__init__`.
- [ ] Entendo o papel de `self`.

---

# 13. Para guardar

A aula não foi sobre decorar comandos.

Foi sobre aprender a enxergar:

```text
DADOS
  ↓
ESTRUTURAS
  ↓
OPERAÇÕES
  ↓
ITERAÇÃO
  ↓
ERROS E INVESTIGAÇÃO
  ↓
ORGANIZAÇÃO DO CÓDIGO
  ↓
OBJETOS
```

Quando você consegue olhar para um programa e identificar essas partes, o código começa a deixar de parecer uma coleção de símbolos e passa a representar **estrutura, intenção e comportamento**.
"""